readers:
  uda:
    type: 'uda'
  fairmast:
    type: 'zarr'
    options:
      base_path: 's3://mast/level1/shots'
      protocol: 'simplecache'
      target_protocol: "s3"
      target_options:
          anon: True 
          endpoint_url: "https://s3.echo.stfc.ac.uk"

writer:
  type: "zarr"
  options:
    zarr_format: 3
    output_path: "/rds/project/rds-mOlK9qn0PlQ/fairmast/upload-tmp/level2"
